name: Glitch Sync

on: [pull_request, push, workflow_dispatch]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Glitch Project
      uses: kanadgupta/glitch-sync@master
      with:
        project-id: '${{ secrets.projectId }}'
        auth-token: '${{ secrets.authToken }}'